language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
install:
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=anyloadump setup.py test
after_success:
  - coveralls
